# WhatATheme
markdown: kramdown
kramdown:
  math_engine: null

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: 欢迎来到 RootCui 的博客！
# Description of the Site
description: RootCui 的博客
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: rootcui@gmail.com
facebook_username: / 
twitter_username: root_career
instagram_username: / 
linkedin_username: / 
github_username:  / 
youtube_channel_id: / 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: 31nsxvzspqu7nrnncobg2zw37j3q

# Google Analytics
google-analytics: / 

# Disqus
disqus-shortname: / 

# Name of the Author
author-name: RootCui
# URL for the Image of the Author
author-image: https://github.com/RootCui/rootcui.github.io/blob/master/assets/images/wechat.jpg?raw=true
# 60 Words About the Author
author-about: 一般路过高中生
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: rootcui.github.io

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
